### ISSUE TITLE
安装付费插件bug AttributeError: 'dict_obj' object has no attribute 'tmp_path'

### ISSUE THREAD

**Issue by mouzhai163** [flucont/btcloud#161]
![error](https://github.com/flucont/btcloud/assets/49009085/b3123a8c-a100-4d65-bca8-23bb5e4bf123)
后端API对接的是开心版本的8.0.4，不知道是不是跟这个有关？ 基本上付费插件都会报这个错

**Comment by mouzhai163** [comment]
REQUEST_DATE: 2024-01-03 12:10:12
 PAN_VERSION: 8.0.4
  OS_VERSION: CentOS  7.5.1804 x86_64(Py3.7.9)
 REMOTE_ADDR: XX.XXX.XXX.XXX
 REQUEST_URI: POST /plugin?action=input_package
REQUEST_FORM: {}
  USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36


Traceback (most recent call last):
  File "/www/server/panel/BTPanel/__init__.py", line 2105, in publicObject
    res = run_obj.run(toObject, defs, get)
  File "/www/server/panel/BTPanel/__init__.py", line 2052, in run
    result = getattr(toObject, get.action)(get)
  File "class/panelPlugin.py", line 76, in input_package
    return self.__input_plugin(get.tmp_path, get.plugin_name,
AttributeError: 'dict_obj' object has no attribute 'tmp_path'

**Comment by mouzhai163** [comment]
采用的NAS搭建开心版本BT，然后在上面运行BTCloud，CF Tunnels穿透，服务器对接，我可以将我的BTCloud开放出来，如果你需要的话，另外我发现运行一键更新脚本，脚本中Btapi_Url变量是http协议，并非https，这个导致我无法运行更新脚本，因为CF穿透是强制HTTPS的 无法修改

**Comment by mouzhai163** [comment]
这个我确实注意到了，我确实用的是HTTPS协议，包括download下载页面都是https  但是只有那个升级文件内部是http，这个我回头再测试一下，然后我重装了对接人家已经安装好的btcloud，但是卸载防火墙报错误，目前就是这两个致命的bug，大佬有计划检测修复一下吗？

**Comment by mouzhai163** [comment]
大佬能提供一下你的环境信息吗？ 我试试看，loc很多debian用户都测试无法卸载插件，我晚点搭建一下我之前的环境开放给你测试下，我发到loc  您方便用服务器测试下吗

**Comment by picasiso** [comment]
debian 10 安装免费插件 的LINUX 免费工具箱也出现这个问题了

**Comment by mouzhai163** [comment]
经过测试，安装了2.2的版本可以使用，原因是开心版本没有更新到最新的8.0.4版本，可能是因为这个导致的，所以我用了2.2，Centos7安装插件和卸载插件没有问题，而且部分三方插件也可以使用，大伙使用的时候注意一下自己的开心版本是几点几的小版本，选择时间相对应的BTCloud即可，感谢大佬的开源项目
