### ISSUE TITLE
一件部署无法使用

### ISSUE THREAD

**Issue by liulang1234** [flucont/btcloud#87]
![image](https://user-images.githubusercontent.com/66832859/219593399-be380846-8a75-4e97-a4d7-4ec464cd5cb6.png)
出错了，面板运行时发生错误！
KeyError: 'content-length'
REQUEST_DATE: 2023-02-17 16:30:30
 PAN_VERSION: 7.9.8
  OS_VERSION: CentOS  7.9.2009 x86_64(Py3.7.9)
 REMOTE_ADDR: 192.168.3.76
 REQUEST_URI: POST /deployment?action=SetupPackage
REQUEST_FORM: {'dname': 'yun_shop', 'site_name': '1.cn', 'php_version': '74'}
  USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Traceback (most recent call last):
  File "/www/server/panel/BTPanel/__init__.py", line 1849, in publicObject
    res = run_obj.run(toObject, defs, get)
  File "/www/server/panel/BTPanel/__init__.py", line 1796, in run
    result = getattr(toObject,get.action)(get)
  File "class/plugin_deployment.py", line 327, in SetupPackage
    if pinfo['versions'][0]['download']: self.DownloadFile(public.GetConfigValue('home') + '/api/Pluginother/get_file?fname=' + pinfo['versions'][0]['download'], packageZip)
  File "class/plugin_deployment.py", line 267, in DownloadFile
    headers_total_size = int(download_res.headers['content-length'])
  File "/www/server/panel/pyenv/lib/python3.7/site-packages/requests/structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
很抱歉，面板运行时意外发生错误，请尝试按以下顺序尝试解除此错误：
修复方案一：在[首页]右上角点击修复面板，并退出面板重新登录。
修复方案二：如上述尝试未能解除此错误，请截图此窗口到宝塔论坛发贴寻求帮助, 论坛地址：https://www.bt.cn/bbs

**Comment by ventusoon** [comment]
同样的问题，请问你解决了吗
