### ISSUE TITLE
我安装了PluginLoader，但是依然提示没有安装，环境和其他步骤全部按照readme操作的

### ISSUE THREAD

**Issue by ventusoon** [flucont/btcloud#97]
## 错误提示
```
Traceback (most recent call last):
  File "/www/server/panel/BTPanel/__init__.py", line 1850, in publicObject
    res = run_obj.run(toObject, defs, get)
  File "/www/server/panel/BTPanel/__init__.py", line 1797, in run
    result = getattr(toObject,get.action)(get)
  File "class/panelController.py", line 80, in model
    import PluginLoader
ModuleNotFoundError: No module named 'PluginLoader'
```
## 系统
```
debian 10
```

**Comment by ventusoon** [comment]
import PluginLoader
ModuleNotFoundError: No module named 'PluginLoader'
\n
Traceback (most recent call last):
  File "/www/server/panel/BT-Task", line 13, in <module>
    import task
  File "/www/server/panel/task.py", line 24, in <module>
    import db
  File "/www/server/panel/class/db.py", line 16, in <module>
    import PluginLoader
ModuleNotFoundError: No module named 'PluginLoader'
\n
Traceback (most recent call last):
  File "/www/server/panel/BT-Task", line 13, in <module>
    import task
  File "/www/server/panel/task.py", line 24, in <module>
    import db
  File "/www/server/panel/class/db.py", line 16, in <module>
    import PluginLoader
ModuleNotFoundError: No module named 'PluginLoader'

**Comment by ventusoon** [comment]
Name: pluginloader
Version: 0.1.3
Summary: Library to manage plugins/extensions in your applications.
Home-page: https://github.com/magmax/python-pluginloader
Author: Miguel Ángel García
Author-email: miguelangel.garcia@gmail.com
License: MIT
Location: /usr/local/lib/python3.9/dist-packages
Requires: 
Required-by:

**Comment by ventusoon** [comment]
> 这个不需要你安装什么其他插件，应该是你的宝塔面板源码少文件了。你是用的第三方云端自带的宝塔安装包还是自己改的？

它自带的

**Comment by ventusoon** [comment]
> 自带的用批量替换脚本之后，我试过没问题啊

那可能是我哪里出错了。。已经放弃了改用破解版了额，不过谢谢回复
